#!/bin/sh

NUM=$(git diff --staged --name-only | grep -c "\.py$")

if [ $NUM ]; then
    STAGED=$(git diff --staged --name-only | grep "\.py$")
    printf "\nFollowing py Files being checked ... \n$STAGED\n"
fi

set -e

printf "\nRun formatting ...\n"
if [ $NUM ]; then
    black $STAGED
    isort $STAGED
    mypy $STAGED
else
    echo "No py files to be formatted!"
fi

printf "\nRun linter ...\n"
if [ $NUM ]; then
    pylint -j 4 $STAGED
else
    echo "No py files to be linted!"
fi

printf "\nRun tests ...\n"
make test
