#!/bin/sh

STAGED=$(git diff --staged --name-only | grep .py)
NUM=$($STAGED | wc -l)

printf "\nFollowing Py Files being checked ... \n$STAGED\n"

set -e

printf "\nRun formatting ...\n"
if [ $NUM ]; then
    black $STAGED
    isort $STAGED
    mypy $STAGED
else
    echo "No py files to be commited!"
fi

printf "\nRun linter ...\n"
if [ $NUM ]; then
    pylint -j 4 $STAGED
else
    echo "No py files to be commited!"
fi

printf "\nRun tests ...\n"
make test
